config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :custom_relation_types
resources :custom_relations

app/models/custom_relation.rb
class CustomRelation < ActiveRecord::Base
  # unloadable
  belongs_to :custom_relation_type
  belongs_to :issue_from, class_name: 'Issue', foreign_key: :issue_from_id
  belongs_to :issue_to, class_name: 'Issue', foreign_key: :issue_to_id

  delegate :title, to: :custom_relation_type, prefix: true, allow_nil: true

  validates :custom_relation_type_id, presence: true
  validates :issue_from_id, presence: true
  validates :issue_to_id, presence: true

  def create_revers_relation
    relation = CustomRelation.create(issue_from_id: issue_to_id, issue_to_id: issue_from_id, custom_relation_type_id: custom_relation_type.reverse_id)
    # relation.save
  end
end

app/models/custom_relation_type.rb
class CustomRelationType < ActiveRecord::Base
  belongs_to :revers_relation_type, class_name: 'CustomRelationType', foreign_key: :reverse_id

  delegate :title, to: :revers_relation_type, prefix: true, allow_nil: true

  validates :title, presence: true

  def has_reverse_relation?
    reverse_id.present?
  end

  def revers_type_id
    reverse_id
  end
end

app/controllers/custom_relation_types_controller.rb
class CustomRelationTypesController < ApplicationController
  before_action :set_relation, only: [:show, :edit, :update, :destroy]

  def new
    @relation = CustomRelationType.new
  end


  def create
    @relation = CustomRelationType.new(custom_relation_type_params)

    respond_to do |format|
      if @relation.save
        format.html { redirect_to '/settings/plugin/custom_issues_relations', notice: 'relation was successfully created.' }
        format.json { render :show, status: :created, location: @relation }
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    puts params.inspect
    respond_to do |format|
      if @relation.update(custom_relation_type_params)
        format.html { redirect_to '/settings/plugin/custom_issues_relations', notice: 'relation was successfully updated.' }
        format.json { render :show, status: :ok, location: @relation }
      else
        format.html { render :edit }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @relation.destroy
    respond_to do |format|
      format.html { redirect_to '/settings/plugin/custom_issues_relations', notice: 'relation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_relation
    @relation = CustomRelationType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def custom_relation_type_params
    params.require(:custom_relation_type).permit(:title, :reverse_id, :order_index)
  end
end

app/controllers/custom_relations_controller.rb
class CustomRelationsController < ApplicationController
  before_action :set_relation, only: [:destroy]



  def create

    @custom_relation = CustomRelation.new(custom_relation_params)

    saved = @custom_relation.save
    if saved && @custom_relation.custom_relation_type.has_reverse_relation?
      @custom_relation.create_revers_relation
    end
    respond_to do |format|
      if saved
        @issue =  @custom_relation.issue_from
        format.html { redirect_to issue_path(@issue) }
        format.js
        format.json { render :show, status: :created, location: @custom_relation }
      else
        format.html { render :new }
        format.js
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def destroy
    @relation.destroy

    respond_to do |format|
      format.html { redirect_to issue_path(@relation.issue_from) }
      format.js
      format.api  { render_api_ok }
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_relation
    @relation = CustomRelation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def custom_relation_params
    params.require(:custom_relation).permit(:issue_from_id, :issue_to_id, :custom_relation_type_id)
  end
end

app/views/custom_relation_types/_form.erb
<%= form_for @relation,  html: {class: "nifty_form"} do |f| %>

    <% if @relation.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @relation.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= l(:field_name)%>
    <%= f.text_field :title %>
    <%= l(:order_index)%>
    <%= f.text_field :order_index %>
    <%= l(:invers_name)%>
    <%= f.select(:reverse_id, options_for_select(CustomRelationType.order(:order_index).all.collect {|p| [ p.title, p.id ] }), { include_blank: true }) %>
    <%= f.submit l(:save) %>
<% end %>

app/views/custom_relation_types/edit.erb
<h3><%= l(:edit_relation_type)%></h3>

<%= render 'form' %>

app/views/custom_relation_types/new.erb
<h3><%= l(:new_relation_type)%></h3>

<%= render 'form' %>

app/views/custom_relations/_table.erb
<div class="contextual">
  <% if User.current.allowed_to?(:manage_issue_relations, @project) %>
      <%= toggle_link l(:button_add), 'new-custom-relation-form', {:focus => 'relation_issue_to_id'} %>
  <% end %>
</div>
<p><strong><%=l(:label_related_issues)%></strong></p>
<% custom_relations = CustomRelation.includes(:custom_relation_type).where(issue_from_id: @issue.id).order('custom_relation_types.order_index')%>
<% if custom_relations.present? %>
    <form>
      <table class="list issues">
        <% custom_relations.each do |relation| %>
            <% other_issue = relation.issue_to %>
            <tr class="issue <%= other_issue.css_classes %>" id="custom-relation-<%= relation.id %>">
              <td class="subject" style="width: 50%">
                <%= "#{relation.custom_relation_type_title} " %>
                <%= link_to_issue(other_issue, :project => Setting.cross_project_issue_relations?) %>
              </td>
              <td class="status"><%= other_issue.status.name %></td>
              <td class="start_date"><%= format_date(other_issue.start_date) %></td>
              <td class="due_date"><%= format_date(other_issue.due_date) %></td>
              <td class="buttons"><%= link_to(l(:label_relation_delete),
                                              custom_relation_path(relation),
                                              :remote => true,
                                              :method => :delete,
                                              :data => {:confirm => l(:text_are_you_sure)},
                                              :title => l(:label_relation_delete),
                                              :class => 'icon-only icon-link-break'
                                      ) if User.current.allowed_to?(:manage_issue_relations, @project) %></td>
            </tr>
        <% end %>
      </table>
    </form>
<% end %>

app/views/custom_relations/create.js.erb
$('#custom_relations').html('<%= escape_javascript(render :partial => 'custom_relations/table') %>');
<% if @custom_relation.errors.empty? %>
  $('#custom_relation_issue_to_id').val('');
  $('#custom_relation_issue_to_id').focus();
<% end %>
$('#new-custom-relation-form').show();

app/views/custom_relations/destroy.js.erb
$('#custom-relation-<%= @relation.id %>').remove();

app/views/hooks_views/_show_related_issues.erb
<hr />
<div id="custom_relations">
  <%= render :partial => 'custom_relations/table' %>
</div>

<% @custom_relation = CustomRelation.new %>
<%= form_for @custom_relation, {:as => :custom_relation, :remote => true,
                              :html => {:id => 'new-custom-relation-form', :style => 'display: none;'}
                      } do |f| %>
    <%= error_messages_for 'custom_relation' %>
    <%= f.hidden_field :issue_from_id, value: "#{@issue.id}"%>
    <p><%= f.select :custom_relation_type_id, options_for_select(CustomRelationType.order(:order_index).all.collect {|p| [ p.title, p.id ] }), {}%>
      <%= l(:label_issue) %> #<%= f.text_field :issue_to_id, :size => 50 %>
      <%= submit_tag l(:button_add) %>
      <%= link_to_function l(:button_cancel), '$("#new-custom-relation-form").hide();'%>
    </p>

    <%= javascript_tag "observeAutocompleteField('custom_relation_issue_to_id', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>

<% end %>

app/views/settings/_relations_settings.erb
<h3><%= l(:manage_relation)%></h3>

<table class="list issues">
  <thead>
  <tr>
    <th><%= l(:field_name) %></th>
    <th><%= l(:invers_name) %></th>
    <th align="center" style="width:10%;"></th>
  </tr>
  </thead>
  <tbody>
  <% CustomRelationType.order(:order_index).all.each do |rel| %>
      <tr id="<%= rel.id %>" class="<%= cycle('odd', 'even') %> hascontextmenu">
        <td><%= rel.title %></td>
        <td><%= rel.revers_relation_type_title %></td>
        <td class="buttons">
          <%= link_to l(:button_edit), edit_custom_relation_type_path(rel),
                      class: 'icon icon-edit' %>
          <%= link_to l(:button_delete), custom_relation_type_path(ids: rel), method: :delete,
                      confirm: l(:text_are_you_sure), class: 'icon icon-del' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>


<%= link_to l(:new_relation_type), new_custom_relation_type_path %>